apiVersion: v1
kind: Deployment
metadata:
  name: agent-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: flai/azdevops-agent
        ports:
        - containerPort: 80
